### ISSUE TITLE
Blatt04/Aufgabe02

### ISSUE THREAD

**Issue by Marco5de** [Marco5de/PVS#1]
Code compiled und funktinoiert soweit.
**ToDo:** 
Code: fc155f3aea281415a600efc9dafdbb52f610b984
- fix einlesen mehrerer Bilder nacheinander
- Verbesserungen am Layout

**Comment by bjthehun** [comment]
1. Fehler sollte gefixt sein

**Comment by Marco5de** [comment]
Funktioniert
